---

- name: Restart solr
  systemd:
    name: solr
    state: restarted
    enabled: yes

- name: Clean downloads
  file:
    path: "{{ solr_source_path }}/solr-{{ solr_version }}.tgz"
    state: absent

- name: Clean docs and examples
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ solr_install_path }}/docs"
    - "{{ solr_install_path }}/example"
  when: not solr_enable_docs
